import { CheckCircle2 } from 'lucide-react';

import { CitationPill } from './CitationPill';
import { ExportToolbar } from './ExportToolbar';
import { cn } from '@/lib/utils';
import type { ResearchReport } from '@/data/zeroAiFixtures';

interface ReportCanvasProps {
  report: ResearchReport;
  onJsonInspect: () => void;
  onNewResearch: () => void;
}

/** COMPLETED state — publication-grade research report with inline citation pills. */
export function ReportCanvas({ report, onJsonInspect, onNewResearch }: ReportCanvasProps) {
  return (
    <div className="flex flex-col gap-6 px-4 py-6">
      {/* User question bubble */}
      <div className="flex justify-end">
        <div className="max-w-[85%] rounded-2xl rounded-br-md border border-primary/25 bg-primary/10 px-4 py-2.5 text-sm leading-relaxed text-foreground">
          {report.prompt}
        </div>
      </div>

      {/* Report card */}
      <article className="max-w-3xl rounded-2xl border bg-card p-5 shadow-xl shadow-black/20 sm:p-7">
        {/* Meta row + actions */}
        <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center">
          <div className="za-mono flex flex-wrap gap-x-3 gap-y-1 text-[10px] tracking-wide text-muted-foreground">
            <span>REPORT {report.id}</span>
            <span aria-hidden="true">/</span>
            <span>DEPTH {report.depth}</span>
            <span aria-hidden="true">/</span>
            <span>{report.durationSec}s</span>
            <span aria-hidden="true">/</span>
            <span>{report.sources.length} SOURCES</span>
          </div>
          <div className="sm:ml-auto">
            <ExportToolbar report={report} onJsonInspect={onJsonInspect} onNewResearch={onNewResearch} />
          </div>
        </div>

        {/* Title */}
        <h1 className="za-serif mt-5 text-[22px] font-semibold leading-snug tracking-tight text-foreground sm:text-[26px]">
          {report.title}
        </h1>

        {/* Abstract highlight card */}
        <div className="mt-4 rounded-xl border-l-2 border-primary/70 bg-primary/5 px-4 py-3.5">
          <span className="za-mono text-[10px] font-bold tracking-[0.2em] text-primary">ABSTRACT</span>
          <p className="za-serif mt-2 text-sm leading-relaxed text-foreground/90">{report.abstract}</p>
        </div>

        {/* Body sections */}
        {report.sections.map((section) => (
          <section key={section.heading} className="mt-6">
            <h2 className="za-serif text-lg font-semibold text-foreground">{section.heading}</h2>
            {section.paragraphs.map((para, i) => (
              <p key={i} className="za-serif mt-3 text-[14px] leading-[1.8] text-foreground/85">
                {para.text}
                {para.citations.map((sourceId) => {
                  const source = report.sources.find((s) => s.id === sourceId);
                  return source ? <CitationPill key={source.id} index={source.id} source={source} /> : null;
                })}
              </p>
            ))}
          </section>
        ))}

        {/* Sources */}
        <section className="mt-7 border-t pt-5">
          <h2 className="za-mono flex items-center gap-2 text-[11px] font-bold tracking-[0.2em] text-muted-foreground">
            <CheckCircle2 className="size-3.5 text-emerald-400" />
            SOURCES · {report.sources.length}
          </h2>
          <ol className="mt-3 space-y-2.5">
            {report.sources.map((source) => (
              <li key={source.id} className="flex gap-3 text-[12px] leading-relaxed">
                <span className="za-mono shrink-0 text-muted-foreground">[{source.id}]</span>
                <span className="text-foreground/80">
                  <span className="font-medium text-foreground">{source.authors}</span>.{' '}
                  <span className="italic">{source.title}</span>. {source.venue} ({source.year}).
                  {source.doi && (
                    <>
                      {' '}
                      <a
                        href={`https://doi.org/${source.doi}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary underline-offset-2 hover:underline"
                      >
                        DOI: {source.doi}
                      </a>
                    </>
                  )}
                </span>
              </li>
            ))}
          </ol>
        </section>

        <p className={cn('za-mono mt-6 border-t pt-4 text-[10px] tracking-wide text-muted-foreground/60')}>
          GENERATED BY 0-AI DEEP RESEARCH WORKSPACE · PHASE 1 MOCK · NOT A REAL CREDENTIAL
        </p>
      </article>
    </div>
  );
}